# Generated by Django 5.2.4 on 2026-07-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("paper_type", models.CharField(blank=True, max_length=60)),
                ("duration", models.PositiveIntegerField(default=90)),
                (
                    "target_score",
                    models.DecimalField(decimal_places=2, default=100, max_digits=7),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="DRAFT", max_length=20),
                ),
                ("instructions", models.TextField(blank=True)),
                ("school_name", models.CharField(blank=True, max_length=180)),
                ("major", models.CharField(blank=True, max_length=120)),
                ("class_name", models.CharField(blank=True, max_length=120)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_type", models.CharField(max_length=20)),
                ("file_format", models.CharField(max_length=10)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("status", models.CharField(default="WAITING", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="papers.paper",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="papers.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PaperQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=1, max_digits=7),
                ),
                ("question_snapshot", models.JSONField(default=dict)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_questions",
                        to="papers.paper",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paper_uses",
                        to="questions.question",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_questions",
                        to="papers.papersection",
                    ),
                ),
            ],
            options={
                "ordering": ["section__sort_order", "sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("question__isnull", False)),
                        fields=("paper", "question"),
                        name="unique_paper_question",
                    )
                ],
            },
        ),
    ]
