<template><div class="page"><div class="page-header"><div><h1 class="page-title">章节与知识点</h1><p class="page-description">按课程维护章节树，并在确认后导入AI识别结果。</p></div><div><el-button @click="router.push('/knowledge-points')">知识点管理</el-button><el-button type="primary" :disabled="!course" @click="openCreate(null)"><Plus/>新增一级章节</el-button></div></div><div class="toolbar card card-body"><el-select v-model="course" placeholder="请选择课程" style="width:260px"><el-option v-for="item in store.courses" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="aiFile" placeholder="选择文件进行AI识别" clearable style="width:280px"><el-option v-for="item in files" :key="item.id" :label="item.original_name" :value="item.id"/></el-select><el-button :loading="extracting" :disabled="!aiFile" @click="aiExtract"><MagicStick/>AI识别章节</el-button></div><div class="card card-body"><PageState :loading="loading" :empty="!tree.length" empty-text="当前课程还没有章节。"><el-tree :data="tree" node-key="id" default-expand-all draggable @node-drop="saveOrder"><template #default="{data}"><div class="tree-node"><span><b>{{data.number}}</b> {{data.name}}</span><span><el-button link @click.stop="openCreate(data)">新增子章节</el-button><el-button link @click.stop="edit(data)">编辑</el-button><el-button link type="danger" @click.stop="remove(data)">删除</el-button></span></div></template></el-tree></PageState></div><el-dialog v-model="dialog" :title="form.id?'编辑章节':'新增章节'" width="500"><el-form :model="form" label-width="90px"><el-form-item label="章节编号"><el-input v-model="form.number" placeholder="如：1.1"/></el-form-item><el-form-item label="章节名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="章节说明"><el-input v-model="form.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog><el-dialog v-model="previewDialog" title="AI章节识别预览" width="760"><el-alert title="可直接编辑JSON中的章节名称、层级或删除错误项；确认导入不会覆盖已有章节。" type="info" show-icon :closable="false"/><el-input v-model="previewText" type="textarea" :rows="18" class="json-editor"/><template #footer><el-button @click="previewDialog=false">取消</el-button><el-button type="primary" @click="confirmPreview">确认导入</el-button></template></el-dialog></div></template>
<script setup>
import{ref,reactive,watch,onMounted}from'vue';import{useRouter}from'vue-router';import{ElMessage,ElMessageBox}from'element-plus';import{knowledgeApi}from'../../api';import{useAppStore}from'../../stores/app';import PageState from'../../components/PageState.vue'
const router=useRouter(),store=useAppStore(),course=ref(''),tree=ref([]),files=ref([]),loading=ref(false),dialog=ref(false),extracting=ref(false),aiFile=ref(''),previewDialog=ref(false),previewText=ref(''),previewId=ref(null),form=reactive({id:null,parent:null,name:'',number:'',description:'',course:null,level:1,sort_order:0})
const load=async()=>{if(!course.value)return;loading.value=true;try{tree.value=await knowledgeApi.chapters({course:course.value});const data=await knowledgeApi.files({course:course.value,status:'SUCCESS',page_size:100});files.value=data.items}finally{loading.value=false}}
watch(course,load)
const openCreate=parent=>{Object.assign(form,{id:null,parent:parent?.id||null,name:'',number:'',description:'',course:course.value,level:(parent?.level||0)+1,sort_order:parent?.children?.length||tree.value.length});dialog.value=true}
const edit=item=>{Object.assign(form,item,{parent:item.parent||null});dialog.value=true}
const save=async()=>{if(!form.name.trim())return ElMessage.warning('请输入章节名称');form.id?await knowledgeApi.updateChapter(form.id,form):await knowledgeApi.createChapter(form);dialog.value=false;ElMessage.success('章节已保存');load()}
const remove=async item=>{await ElMessageBox.confirm(`删除“${item.name}”会同时删除其子章节，是否继续？`,'删除章节',{type:'warning'});await knowledgeApi.deleteChapter(item.id);load()}
const flatten=(nodes,parent=null,out=[])=>{nodes.forEach((node,index)=>{out.push({id:node.id,parent,sort_order:index,level:parent?2:1});if(node.children)flatten(node.children,node.id,out)});return out}
const saveOrder=async()=>{await knowledgeApi.reorder({items:flatten(tree.value)});ElMessage.success('章节顺序已保存')}
const aiExtract=async()=>{extracting.value=true;try{const data=await knowledgeApi.aiChapters({file_id:aiFile.value});previewId.value=data.preview_id;previewText.value=JSON.stringify(data.result,null,2);previewDialog.value=true}finally{extracting.value=false}}
const confirmPreview=async()=>{let result;try{result=JSON.parse(previewText.value)}catch{return ElMessage.error('预览JSON格式不正确，请检查逗号、引号和括号。')}await knowledgeApi.confirmChapters({preview_id:previewId.value,result});previewDialog.value=false;ElMessage.success('章节已导入');load()}
onMounted(async()=>{await store.loadCourses();course.value=store.courses[0]?.id||''})
</script>
<style scoped>.tree-node{width:100%;display:flex;justify-content:space-between;align-items:center;padding-right:12px}.el-tree{--el-tree-node-content-height:46px}.json-editor{margin-top:14px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace}</style>
