import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="AgentDefinition", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("key", models.CharField(max_length=80, unique=True)), ("name", models.CharField(max_length=120)), ("role", models.TextField()), ("model_setting_key", models.CharField(default="chat_model", max_length=60)), ("prompt_key", models.CharField(blank=True, max_length=80)), ("enabled", models.BooleanField(default=True)), ("config", models.JSONField(blank=True, default=dict)), ("sort_order", models.PositiveSmallIntegerField(default=0)), ("updated_at", models.DateTimeField(auto_now=True))], options={"ordering": ["sort_order", "id"]}),
        migrations.CreateModel(name="AgentWorkflowRun", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("workflow_type", models.CharField(db_index=True, max_length=60)), ("business_type", models.CharField(db_index=True, max_length=60)), ("business_id", models.PositiveBigIntegerField(blank=True, db_index=True, null=True)), ("status", models.CharField(choices=[(x, x) for x in ["WAITING", "RUNNING", "AWAITING_REVIEW", "SUCCESS", "FAILED", "CANCELLED", "INTERRUPTED"]], db_index=True, default="WAITING", max_length=30)), ("priority", models.PositiveSmallIntegerField(db_index=True, default=50)), ("progress", models.PositiveSmallIntegerField(default=0)), ("current_agent", models.CharField(blank=True, max_length=80)), ("quality_mode", models.CharField(choices=[(x, x) for x in ["FAST", "STANDARD", "DEEP"]], default="STANDARD", max_length=20)), ("thread_id", models.CharField(max_length=80, unique=True)), ("input_data", models.JSONField(blank=True, default=dict)), ("state_summary", models.JSONField(blank=True, default=dict)), ("result", models.JSONField(blank=True, default=dict)), ("cancel_requested", models.BooleanField(default=False)), ("retry_count", models.PositiveSmallIntegerField(default=0)), ("heartbeat_at", models.DateTimeField(blank=True, null=True)), ("started_at", models.DateTimeField(blank=True, null=True)), ("finished_at", models.DateTimeField(blank=True, null=True)), ("error_message", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="AgentStepRun", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("agent_key", models.CharField(max_length=80)), ("step_name", models.CharField(max_length=120)), ("status", models.CharField(db_index=True, default="WAITING", max_length=30)), ("attempt", models.PositiveSmallIntegerField(default=1)), ("input_summary", models.JSONField(blank=True, default=dict)), ("output_summary", models.JSONField(blank=True, default=dict)), ("metrics", models.JSONField(blank=True, default=dict)), ("error_message", models.TextField(blank=True)), ("started_at", models.DateTimeField(blank=True, null=True)), ("finished_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="agents.agentworkflowrun"))], options={"ordering": ["created_at", "id"]}),
        migrations.CreateModel(name="AgentArtifact", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("artifact_type", models.CharField(db_index=True, max_length=60)), ("created_by", models.CharField(max_length=80)), ("version", models.PositiveSmallIntegerField(default=1)), ("content", models.JSONField(default=dict)), ("is_current", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="agents.agentworkflowrun"))], options={"ordering": ["artifact_type", "-version"]}),
        migrations.CreateModel(name="AgentMetric", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("agent_key", models.CharField(max_length=80)), ("model_name", models.CharField(blank=True, max_length=120)), ("call_count", models.PositiveIntegerField(default=0)), ("duration_ms", models.PositiveIntegerField(default=0)), ("input_chars", models.PositiveIntegerField(default=0)), ("output_chars", models.PositiveIntegerField(default=0)), ("success", models.BooleanField(default=True)), ("rework_count", models.PositiveSmallIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("workflow", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metrics", to="agents.agentworkflowrun"))]),
        migrations.AddIndex(model_name="agentworkflowrun", index=models.Index(fields=["status", "priority", "created_at"], name="agents_agen_status_9b52e5_idx")),
        migrations.AddConstraint(model_name="agentsteprun", constraint=models.UniqueConstraint(fields=("workflow", "agent_key", "attempt"), name="unique_agent_step_attempt")),
        migrations.AddConstraint(model_name="agentartifact", constraint=models.UniqueConstraint(fields=("workflow", "artifact_type", "version"), name="unique_agent_artifact_version")),
    ]
