# Generated by Django 5.2.4 on 2026-07-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("number", models.CharField(blank=True, max_length=40)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="courses.course",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="knowledge.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="knowledge_files/%Y/%m/")),
                ("file_type", models.CharField(max_length=20)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("WAITING", "WAITING"),
                            ("PARSING", "PARSING"),
                            ("CLEANING", "CLEANING"),
                            ("CHUNKING", "CHUNKING"),
                            ("VECTORIZING", "VECTORIZING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                            ("DISABLED", "DISABLED"),
                            ("INTERRUPTED", "INTERRUPTED"),
                        ],
                        db_index=True,
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                ("parse_progress", models.PositiveSmallIntegerField(default=0)),
                ("char_count", models.PositiveIntegerField(default=0)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("parse_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_files",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("importance", models.CharField(default="一般", max_length=20)),
                ("difficulty", models.CharField(default="中等", max_length=20)),
                ("source_type", models.CharField(default="MANUAL", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_points",
                        to="knowledge.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_points",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ParseTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="WAITING", max_length=20),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=120)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "knowledge_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parse_tasks",
                        to="knowledge.knowledgefile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("char_count", models.PositiveIntegerField(default=0)),
                (
                    "vector_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("vector_status", models.CharField(default="PENDING", max_length=20)),
                ("vector_error", models.TextField(blank=True)),
                ("embedding_model", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chunks",
                        to="knowledge.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_chunks",
                        to="courses.course",
                    ),
                ),
                (
                    "knowledge_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.knowledgefile",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgePointChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relevance_score", models.FloatField(default=1.0)),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_links",
                        to="knowledge.knowledgepoint",
                    ),
                ),
                (
                    "text_chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_links",
                        to="knowledge.textchunk",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["course", "parent", "sort_order"],
                name="knowledge_c_course__97e3eb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgefile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("course", "content_hash"),
                name="unique_active_course_file_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgepoint",
            constraint=models.UniqueConstraint(
                fields=("course", "name", "chapter"),
                name="unique_course_chapter_knowledge_point",
            ),
        ),
        migrations.AddConstraint(
            model_name="textchunk",
            constraint=models.UniqueConstraint(
                fields=("knowledge_file", "chunk_index"), name="unique_file_chunk_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgepointchunk",
            constraint=models.UniqueConstraint(
                fields=("knowledge_point", "text_chunk"), name="unique_knowledge_chunk"
            ),
        ),
    ]
