# Generated by Django 5.2.4 on 2026-07-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="WAITING", max_length=30),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("config", models.JSONField(default=dict)),
                ("prompt", models.TextField(blank=True)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("embedding_model", models.CharField(blank=True, max_length=120)),
                ("retrieved_chunks", models.JSONField(default=list)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_tasks",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_type", models.CharField(db_index=True, max_length=40)),
                ("stem", models.TextField()),
                ("answer", models.JSONField(default=list)),
                ("analysis", models.TextField(blank=True)),
                ("scoring_points", models.JSONField(default=list)),
                (
                    "difficulty",
                    models.CharField(db_index=True, default="中等", max_length=20),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=1, max_digits=7),
                ),
                ("source_type", models.CharField(default="MANUAL", max_length=20)),
                ("source_summary", models.TextField(blank=True)),
                ("source_chunk_ids", models.JSONField(default=list)),
                ("grounding_score", models.FloatField(blank=True, null=True)),
                ("generation_model", models.CharField(blank=True, max_length=120)),
                (
                    "review_status",
                    models.CharField(db_index=True, default="PENDING", max_length=30),
                ),
                ("ai_review_score", models.FloatField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("is_demo", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="knowledge.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.course",
                    ),
                ),
                (
                    "generation_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="questions.generationtask",
                    ),
                ),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="knowledge.knowledgepoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=10)),
                ("content", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_type", models.CharField(max_length=20)),
                ("passed", models.BooleanField(default=False)),
                ("score", models.FloatField(default=0)),
                ("issues", models.JSONField(default=list)),
                ("suggestions", models.JSONField(default=list)),
                ("revised_question", models.JSONField(blank=True, null=True)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="questions.question",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["course", "review_status", "question_type", "difficulty"],
                name="questions_q_course__59f7de_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "label"), name="unique_question_option_label"
            ),
        ),
    ]
