<template>
  <div class="page agent-center">
    <div class="page-header">
      <div><span class="agent-kicker">本地协作网络</span><h1 class="page-title">多智能体中心</h1><p class="page-description">查看检索、命题、校验、修订和组卷智能体的分工与执行记录。</p></div>
      <el-button @click="load"><Refresh />刷新状态</el-button>
    </div>
    <div class="network card">
      <div class="network-copy"><span>当前调度原则</span><h2>一条可追溯的教学内容生产线</h2><p>每个节点只处理自己擅长的任务，下一个节点会核对上一步的结果。本地模型串行执行，避免争抢内存。</p></div>
      <div class="network-track" aria-label="出题智能体流程"><template v-for="(node,index) in flow" :key="node.key"><div class="flow-node"><span>{{index+1}}</span><b>{{node.name}}</b><small>{{node.note}}</small></div><div v-if="index<flow.length-1" class="flow-line"><i /></div></template></div>
    </div>
    <div class="metric-grid agent-metrics">
      <div class="card metric-card"><div><span class="metric-label">全部工作流</span><div class="metric-value">{{stats.total||0}}</div></div></div>
      <div class="card metric-card"><div><span class="metric-label">正在协作</span><div class="metric-value active">{{stats.running||0}}</div></div></div>
      <div class="card metric-card"><div><span class="metric-label">等待教师确认</span><div class="metric-value review">{{stats.awaiting_review||0}}</div></div></div>
      <div class="card metric-card"><div><span class="metric-label">完成率</span><div class="metric-value">{{stats.success_rate||0}}%</div></div></div>
    </div>
    <section class="agent-grid">
      <article v-for="agent in agents" :key="agent.id" class="agent-card card">
        <div class="agent-card-head"><div class="agent-glyph">{{glyph(agent.key)}}</div><el-switch :model-value="agent.enabled" @change="value=>toggle(agent,value)" /></div>
        <span class="agent-order">AGENT {{String(agent.sort_order/10).padStart(2,'0')}}</span><h3>{{agent.name}}</h3><p>{{agent.role}}</p>
        <div class="agent-meta"><span>{{modelLabel(agent.model_setting_key)}}</span><el-button link type="primary" @click="openSettings(agent)">参数设置</el-button><b :class="{off:!agent.enabled}">{{agent.enabled?'已启用':'已停用'}}</b></div>
      </article>
    </section>
    <div class="card workflow-table">
      <div class="card-header"><span class="card-title">最近工作流</span><el-select v-model="status" clearable placeholder="全部状态" style="width:150px" @change="loadRuns"><el-option v-for="item in statuses" :key="item" :label="item" :value="item" /></el-select></div>
      <PageState :loading="loading" :empty="!runs.length" empty-text="还没有智能体执行记录。">
        <el-table :data="runs"><el-table-column prop="business_name" label="任务" min-width="220" /><el-table-column label="类型" width="150"><template #default="s">{{typeLabel(s.row.workflow_type)}}</template></el-table-column><el-table-column label="当前智能体" min-width="170"><template #default="s">{{agentName(s.row.current_agent)}}</template></el-table-column><el-table-column label="质量模式" width="100"><template #default="s">{{modeLabel(s.row.quality_mode)}}</template></el-table-column><el-table-column label="进度" width="150"><template #default="s"><el-progress :percentage="s.row.progress" /></template></el-table-column><el-table-column label="状态" width="130"><template #default="s"><StatusTag :value="s.row.status" /></template></el-table-column><el-table-column label="操作" width="90"><template #default="s"><el-button link type="primary" @click="router.push(`/agents/workflows/${s.row.id}`)">查看轨迹</el-button></template></el-table-column></el-table>
      </PageState>
    </div>
    <el-dialog v-model="dialog" :title="`${editing.name||''}·参数设置`" width="520px"><el-form label-position="top"><el-form-item label="指定本地模型"><el-select v-model="agentForm.model" clearable placeholder="跟随系统默认模型" style="width:100%"><el-option v-for="model in models" :key="model" :label="model" :value="model" /></el-select></el-form-item><div class="form-grid"><el-form-item label="审核通过分数"><el-input-number v-model="agentForm.pass_score" :min="0" :max="100" /></el-form-item><el-form-item label="知识忠实度"><el-input-number v-model="agentForm.grounding_threshold" :min="0" :max="1" :step=".05" /></el-form-item><el-form-item label="最大修订次数"><el-input-number v-model="agentForm.max_revisions" :min="0" :max="3" /></el-form-item></div><el-alert title="留空模型时，智能体会跟随系统默认配置。" type="info" :closable="false" show-icon /></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="saveSettings">保存智能体参数</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import{ref,reactive,onMounted}from'vue';import{useRouter}from'vue-router';import{ElMessage}from'element-plus';import{agentsApi,settingsApi}from'../../api';import PageState from'../../components/PageState.vue';import StatusTag from'../../components/StatusTag.vue';
const router=useRouter(),agents=ref([]),runs=ref([]),stats=ref({}),loading=ref(true),status=ref(''),dialog=ref(false),editing=ref({}),models=ref([]),agentForm=reactive({model:'',pass_score:80,grounding_threshold:.75,max_revisions:1});
const statuses=['WAITING','RUNNING','AWAITING_REVIEW','SUCCESS','FAILED','CANCELLED','INTERRUPTED'];
const flow=[{key:'retrieval_planner',name:'证据检索',note:'RRF + MMR'},{key:'question_author',name:'专项命题',note:'题目·答案·解析'},{key:'answer_reviewer',name:'独立校验',note:'依据一致性'},{key:'rule_similarity',name:'规则去重',note:'Hash + 语义'},{key:'quality_reviewer',name:'教师确认',note:'最终入库'}];
const glyph=key=>({supervisor:'总',retrieval_planner:'证',question_author:'题',answer_reviewer:'答',rule_similarity:'检',quality_reviewer:'审',question_reviser:'修',knowledge_curator:'知',paper_planner:'规',paper_selector:'选',paper_evaluator:'评'}[key]||'智');
const modelLabel=key=>({chat_model:'出题模型',review_model:'审核模型',knowledge_model:'知识模型',embedding_model:'Embedding'}[key]||key);const modeLabel=v=>({FAST:'快速',STANDARD:'标准',DEEP:'深度'}[v]||v);const typeLabel=v=>({QUESTION_GENERATION:'智能出题',PAPER_PLAN:'组卷规划',PAPER_SELECTION:'组卷选题',PAPER_QUALITY:'试卷评估'}[v]||v);const agentName=key=>agents.value.find(x=>x.key===key)?.name||key||'等待分配';
const loadRuns=async()=>{const data=await agentsApi.workflows({status:status.value||undefined,page_size:20});runs.value=data.items||data};const load=async()=>{loading.value=true;try{[agents.value,stats.value]=await Promise.all([agentsApi.list(),agentsApi.statistics()]);await loadRuns()}finally{loading.value=false}};const toggle=async(agent,value)=>{await agentsApi.update(agent.id,{enabled:value});agent.enabled=value;ElMessage.success(`${agent.name}已${value?'启用':'停用'}`)};const openSettings=async agent=>{editing.value=agent;Object.assign(agentForm,{model:agent.config?.model||'',pass_score:agent.config?.pass_score??80,grounding_threshold:agent.config?.grounding_threshold??.75,max_revisions:agent.config?.max_revisions??1});if(!models.value.length){try{models.value=await settingsApi.models()}catch{models.value=[]}}dialog.value=true};const saveSettings=async()=>{const updated=await agentsApi.update(editing.value.id,{config:{...agentForm}});Object.assign(editing.value,updated);dialog.value=false;ElMessage.success('智能体参数已保存')};onMounted(load);
</script>
<style scoped>
.agent-kicker{display:block;margin-bottom:6px;color:#0f8e8e;font-size:12px;font-weight:750;letter-spacing:.16em}.network{position:relative;padding:25px;overflow:hidden;background:linear-gradient(120deg,#f8fbff 0,#fff 58%,#f1fbfa 100%)}.network:after{content:'';position:absolute;right:-70px;top:-100px;width:260px;height:260px;border:1px solid rgba(19,194,194,.17);border-radius:50%;box-shadow:0 0 0 34px rgba(19,194,194,.035),0 0 0 72px rgba(22,119,255,.025)}.network-copy{position:relative;z-index:1;max-width:670px}.network-copy>span{color:var(--primary);font-size:12px;font-weight:700}.network-copy h2{margin:5px 0;font-size:20px}.network-copy p{margin:0;color:var(--text-secondary)}.network-track{position:relative;z-index:1;display:flex;align-items:center;margin-top:24px}.flow-node{width:150px;min-height:92px;padding:13px;border:1px solid #dfe8f4;border-radius:11px;background:rgba(255,255,255,.94)}.flow-node>span{float:right;color:#8a97aa;font:700 11px monospace}.flow-node b,.flow-node small{display:block}.flow-node b{margin-top:8px}.flow-node small{margin-top:4px;color:var(--text-secondary);font-size:11px}.flow-line{flex:1;height:20px;display:grid;place-items:center}.flow-line i{display:block;width:100%;height:1px;background:linear-gradient(90deg,#91caff,#56d6cf);position:relative}.flow-line i:after{content:'';position:absolute;right:0;top:-3px;border-left:6px solid #56d6cf;border-top:4px solid transparent;border-bottom:4px solid transparent}.agent-metrics{grid-template-columns:repeat(4,1fr);margin:18px 0}.agent-metrics .metric-card{cursor:default}.metric-value.active{color:var(--primary)}.metric-value.review{color:#d98708}.agent-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px;margin-bottom:18px}.agent-card{padding:18px;min-height:208px}.agent-card-head{display:flex;justify-content:space-between}.agent-glyph{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;color:#087f80;background:#e8f9f8;font-size:17px;font-weight:800}.agent-order{display:block;margin-top:15px;color:#93a0b2;font:700 10px monospace;letter-spacing:.09em}.agent-card h3{margin:3px 0 7px;font-size:16px}.agent-card p{min-height:48px;margin:0;color:var(--text-secondary);font-size:12px;line-height:1.65}.agent-meta{display:flex;justify-content:space-between;margin-top:15px;padding-top:12px;border-top:1px solid var(--border);color:var(--text-secondary);font-size:11px}.agent-meta b{color:var(--success)}.agent-meta b.off{color:#98a2b3}.workflow-table{overflow:hidden}@media(max-width:1450px){.agent-grid{grid-template-columns:repeat(3,1fr)}}
</style>
