<template>
  <div class="shell" :class="{collapsed:store.collapsed}">
    <aside class="sidebar">
      <div class="brand"><div class="brand-mark"><Reading /></div><div class="brand-copy"><strong>知识库智能出题与<br>组卷系统</strong></div></div>
      <nav aria-label="主导航"><router-link v-for="item in menus" :key="item.path" :to="item.path" class="nav-item"><el-icon><component :is="item.icon" /></el-icon><span>{{item.label}}</span></router-link></nav>
      <div class="sidebar-tip" v-if="!store.collapsed"><div class="tip-title"><el-icon><Opportunity /></el-icon> 使用小贴士</div><p>完善知识库可以帮助AI生成依据更充分的题目。</p><router-link to="/knowledge/upload">开始上传资料 →</router-link></div>
      <div class="local-status"><Monitor/><div v-if="!store.collapsed"><strong>本地工作空间</strong><span><i class="status-dot" :class="{ok:store.health.database}"></i> 数据库 {{store.health.database?'正常':'异常'}}</span><span><i class="status-dot" :class="{ok:store.health.ollama}"></i> Ollama {{store.health.ollama?'在线':'离线'}}</span><span><i class="status-dot" :class="{ok:store.health.worker}"></i> Worker {{store.health.worker?'正常':'待检查'}}</span></div></div>
    </aside>
    <main class="main"><header class="topbar"><button class="collapse-btn" @click="store.toggle" aria-label="折叠侧边栏"><Fold v-if="!store.collapsed"/><Expand v-else/></button><h2>{{route.meta.title}}</h2><div class="top-actions"><el-autocomplete v-model="search" :fetch-suggestions="searchSuggestions" placeholder="搜索课程、文件、题目、试卷..." clearable @select="item=>router.push(item.route)"><template #prefix><el-icon><Search/></el-icon></template></el-autocomplete><el-dropdown @command="router.push"><el-button><CirclePlus/> 快速创建 <ArrowDown/></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="/knowledge/upload">上传知识库</el-dropdown-item><el-dropdown-item command="/generation/create">AI智能出题</el-dropdown-item><el-dropdown-item command="/papers/create">创建试卷</el-dropdown-item></el-dropdown-menu></template></el-dropdown><div class="model-pill"><span class="status-dot" :class="{ok:store.health.ollama}"></span><span>{{store.health.current_model||'未配置模型'}}</span></div><div class="local-pill"><Monitor/> 本地工作台</div></div></header><router-view v-slot="{Component}"><transition name="fade" mode="out-in"><component :is="Component"/></transition></router-view></main>
  </div>
</template>
<script setup>
import {ref,onMounted,onUnmounted} from 'vue';import {useRoute,useRouter} from 'vue-router';import {useAppStore} from '../stores/app';import {dashboardApi} from '../api'
const store=useAppStore(),route=useRoute(),router=useRouter(),search=ref('');let timer
const menus=[{path:'/dashboard',label:'首页工作台',icon:'HomeFilled'},{path:'/courses',label:'课程管理',icon:'Collection'},{path:'/knowledge/files',label:'知识库管理',icon:'Document'},{path:'/chapters',label:'章节与知识点',icon:'Notebook'},{path:'/generation/create',label:'AI智能出题',icon:'EditPen'},{path:'/agents',label:'多智能体中心',icon:'Share'},{path:'/questions',label:'题库管理',icon:'Tickets'},{path:'/papers',label:'试卷管理',icon:'Memo'},{path:'/settings',label:'系统设置',icon:'Setting'}]
const searchSuggestions=async(q,cb)=>{if(!q)return cb([]);try{const r=await dashboardApi.search(q);cb(r.map(x=>({...x,value:x.title})))}catch{cb([])}}
onMounted(()=>{store.refreshHealth();timer=setInterval(store.refreshHealth,30000)});onUnmounted(()=>clearInterval(timer))
</script>
<style scoped>
.shell{min-height:100vh}.sidebar{position:fixed;inset:0 auto 0 0;width:var(--sidebar);background:#fff;border-right:1px solid var(--border);z-index:20;display:flex;flex-direction:column;transition:width .22s ease}.main{margin-left:var(--sidebar);min-height:100vh;transition:margin .22s ease}.collapsed{--sidebar:76px}.brand{height:86px;display:flex;align-items:center;gap:12px;padding:0 20px;overflow:hidden}.brand-mark{width:42px;height:42px;border-radius:10px;background:linear-gradient(145deg,#2085ff,#0768e6);color:#fff;display:grid;place-items:center;flex:none;box-shadow:0 7px 16px rgba(22,119,255,.22)}.brand-mark svg{width:25px}.brand-copy{font-size:16px;line-height:1.35;white-space:nowrap}.nav-item{height:48px;margin:3px 14px;padding:0 17px;border-radius:9px;display:flex;align-items:center;gap:14px;color:#59677e;font-weight:500;white-space:nowrap;overflow:hidden}.nav-item .el-icon{font-size:20px;flex:none}.nav-item:hover{background:#f5f8fc;color:var(--primary)}.nav-item.router-link-active{background:var(--primary-light);color:var(--primary);font-weight:650}.sidebar-tip{margin:auto 19px 16px;padding:16px;border:1px solid #d8e7fb;border-radius:10px;background:#f8fbff;color:#627089}.tip-title{color:var(--primary);font-weight:650;display:flex;align-items:center;gap:7px}.sidebar-tip p{font-size:12px}.sidebar-tip a{font-size:12px;color:var(--primary)}.local-status{border-top:1px solid var(--border);padding:18px 20px;display:flex;gap:12px;align-items:flex-start;overflow:hidden}.local-status>svg{width:22px;color:var(--primary);flex:none}.local-status strong,.local-status span{display:block;white-space:nowrap}.local-status span{font-size:11px;color:var(--text-secondary);margin-top:5px}.local-status .status-dot{margin-right:5px}.topbar{height:var(--header);background:#fff;border-bottom:1px solid var(--border);display:flex;align-items:center;padding:0 28px;position:sticky;top:0;z-index:10}.topbar h2{font-size:20px;margin:0 0 0 14px}.collapse-btn{border:0;background:transparent;width:40px;height:40px;border-radius:8px;display:grid;place-items:center;cursor:pointer;color:#6a768a}.collapse-btn:hover{background:#f2f5f9}.collapse-btn svg{width:20px}.top-actions{margin-left:auto;display:flex;align-items:center;gap:12px}.top-actions :deep(.el-autocomplete){width:280px}.model-pill,.local-pill{height:38px;padding:0 12px;border:1px solid var(--border);border-radius:9px;display:flex;align-items:center;gap:8px;color:#4f5c70;white-space:nowrap}.local-pill svg{width:17px;color:var(--primary)}.top-actions :deep(.el-button svg){width:16px;margin-right:5px}@media(max-width:1350px){.local-pill{display:none}.top-actions :deep(.el-autocomplete){width:230px}}
</style>
