# Generated by Django 5.2.4 on 2026-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="课程名称")),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="课程编号"),
                ),
                ("description", models.TextField(blank=True, verbose_name="课程简介")),
                (
                    "grade",
                    models.CharField(blank=True, max_length=80, verbose_name="适用年级"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=120, verbose_name="适用专业"),
                ),
                (
                    "cover",
                    models.ImageField(blank=True, upload_to="course_covers/%Y/%m/"),
                ),
                ("remark", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "使用中"), ("ARCHIVED", "已归档")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_deleted", "status"],
                        name="courses_cou_is_dele_ceb41b_idx",
                    )
                ],
            },
        ),
    ]
